# vi:ft=dockerfile
FROM centos:7

# SYSTEM
RUN yum clean all
RUN yum upgrade -y
RUN yum install -y curl wget which
RUN yum install -y sudo

# ENVIRONMENT
RUN yum install -y git perl ruby
RUN yum install -y perl-Data-Dumper perl-IPC-Cmd
RUN yum install -y gcc gcc-c++ make
RUN yum install -y java-1.8.0-openjdk ant ant-junit maven
RUN yum install -y rpm-build createrepo

# USERS
RUN useradd -ms /bin/bash -G wheel build
RUN sed -i -e '/^%wheel/s/)\s*ALL$/) NOPASSWD: ALL/' /etc/sudoers

# Use a newer git
RUN yum install -y zlib-devel gettext curl-devel
RUN wget "https://www.kernel.org/pub/software/scm/git/git-2.9.5.tar.gz" -O - | tar --no-same-owner -xzf - -C /root
RUN cd /root/git-2.9.5 && ./configure --without-tcltk
RUN make -C /root/git-2.9.5
RUN make -C /root/git-2.9.5 install
RUN yum erase -y zlib-devel gettext
RUN yum erase -y git
RUN rm -rf /root/git-2.9.5

# REDUCE PRIVILEGE
USER build
WORKDIR /home/build
