version: 2

############################################################################

references:
   devcore_job_steps: &devcore_job_steps
      steps:
         - checkout
         - setup_remote_docker:
            version: 17.09.0-ce
         - restore_cache:
            keys:
               - v1-{{.Environment.CIRCLE_JOB}}-{{.Branch}}
            paths:
               - /caches
         - run:
            name: Creating image
            command: |
               mkdir -p /caches
               apk update
               apk add make
               make IMAGES=$CIRCLE_JOB CACHES_DIR=/caches
         - save_cache:
            key: v1-{{.Environment.CIRCLE_JOB}}-{{.Branch}}-{{epoch}}
            paths:
               - /caches
         - deploy:
            name: Pushing image
            command: |
               if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]
               then
                  echo "Docker User: $DOCKER_USER"
                  docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
                  make IMAGES=$CIRCLE_JOB CACHES_DIR=/caches push
               fi

   std_filters: &std_filters
      filters:
         branches:
            only:
               - master
               - develop

############################################################################

jobs:
   core-ubuntu:
      working_directory: ~/zm-base-os
      docker:
         - image: docker:git
      <<: *devcore_job_steps

   devcore-ubuntu-16.04:
      working_directory: ~/zm-base-os
      docker:
         - image: docker:git
      <<: *devcore_job_steps

   devcore-ubuntu-14.04:
      working_directory: ~/zm-base-os
      docker:
         - image: docker:git
      <<: *devcore_job_steps

   devcore-ubuntu-12.04:
      working_directory: ~/zm-base-os
      docker:
         - image: docker:git
      <<: *devcore_job_steps

   devcore-centos-6:
      working_directory: ~/zm-base-os
      docker:
         - image: docker:git
      <<: *devcore_job_steps

   devcore-centos-7:
      working_directory: ~/zm-base-os
      docker:
         - image: docker:git
      <<: *devcore_job_steps

############################################################################

workflows:
   version: 2
   build_and_deploy:
      jobs:
         - devcore-ubuntu-16.04:
            <<: *std_filters

         - devcore-ubuntu-14.04:
            <<: *std_filters

         - devcore-ubuntu-12.04:
            <<: *std_filters

         - devcore-centos-6:
            <<: *std_filters

         - devcore-centos-7:
            <<: *std_filters

         - core-ubuntu:
            <<: *std_filters
